development:
  adapter: postgresql
  encoding: unicode
  database: ga_development1
  pool: 5
  host: localhost
  username: postgres
  password: 08820

production:
  adapter: postgresql
  encoding: unicode
  database: ga_production
  pool: 5
  host: localhost
  username: postgres
  password: 08820